name: new-workflow-2

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout      
        id: checkout
        uses: actions/checkout@v7

      - name: Setup pnpm    
        uses: pnpm/action-setup@v6        

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
            node-version: "24.x"

      - run: make setup
      - run: make lint
      - run: make test
        


      - name: Cypress run 
        uses: cypress-io/github-action@v7
        with:
            install: false
   

      - name: Print Hello from Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release

